logging:
  level:
    org:
      hibernate:
        SQL: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
mi:
  valor: Valor en el application.properties
server:
  port: ${PORT:8080}
spring:
  application:
    name: demo
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/sakila
    username: root
  profiles:
    active: test
